import "./globals.css";
import type { Metadata } from "next";
import { Montserrat } from "@next/font/google";
import { Inter } from "next/font/google";
import { Providers } from "@/context/redux.provider";
import Header from "./components/Header";
import { AspirationContext,AspirationProvider } from "@/context/aspiration.provider";
import Footer from "./components/Footer";

const monstserrat = Montserrat({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-monstserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className="">
      <body className={`${monstserrat.className} min-h-screen flex flex-col`}>
        <Providers>
          <Header />
          <AspirationProvider>
          {children}
          </AspirationProvider>
          <Footer/>
        </Providers>
      </body>
    </html>
  );
}
